### ISSUE TITLE
🐞 Dubious ownership

### ISSUE THREAD

**Issue by jacobwoffenden** [ministryofjustice/.devcontainer#120]
When starting a fresh container locally (haven't tested Codespaces yet), the following is returned from `git status`:
```bash
fatal: detected dubious ownership in repository at '/workspaces/user-guidance'
To add an exception for this directory, call:

        git config --global --add safe.directory /workspaces/user-guidance
```

**Comment by Gary-H9** [comment]
Raised [this PR](https://github.com/ministryofjustice/.devcontainer/pull/123) to resolve this issue.

**Comment by jacobwoffenden** [comment]
https://github.com/ministryofjustice/.devcontainer/pull/138 might've resolved this particular bug

**Comment by jacobwoffenden** [comment]
Resolved by https://github.com/ministryofjustice/.devcontainer/pull/138
